DELETE FROM "book"
WHERE title IN (
    'Harry Potter and the Philosophers Stone',
    'A Game of Thrones',
    'The Hobbit',
    'Good Omens',
    'American Gods',
    'Foundation',
    '2001: A Space Odyssey',
    'The Hitchhikers Guide to the Galaxy',
    'Murder on the Orient Express',
    'The Shining',
    'The Handmaids Tale',
    'Do Androids Dream of Electric Sheep?',
    'The Da Vinci Code',
    'The Hunger Games',
    'To Kill a Mockingbird',
    'The Great Gatsby',
    'The Old Man and the Sea',
    'Adventures of Huckleberry Finn',
    'War and Peace',
    'Crime and Punishment',
    'Brave New World',
    'The Catcher in the Rye',
    'The Road',
    'Slaughterhouse-Five',
    'The Brothers Karamazov',
    'The Wind-Up Bird Chronicle',
    '1984',
    'Animal Farm',
    'Frankenstein',
    'The Picture of Dorian Gray',
    'The Kite Runner',
    'Life of Pi',
    'The Book Thief',
    'The Alchemist',
    'The Night Circus',
    'Gone Girl',
    'Pride and Prejudice',
    'The Fault in Our Stars',
    'The Maze Runner',
    'The Talisman',
    'The Long Earth',
    'Sleeping Beauties',
    'The Mongoliad',
    'Raising Steam',
    'The Black Prism',
    'Dune',
    'Dracula'
);

DELETE FROM "author"
WHERE name IN (
    'J.K. Rowling',
    'George R.R. Martin',
    'J.R.R. Tolkien',
    'Neil Gaiman',
    'Terry Pratchett',
    'Isaac Asimov',
    'Arthur C. Clarke',
    'Douglas Adams',
    'Agatha Christie',
    'Stephen King',
    'Margaret Atwood',
    'Philip K. Dick',
    'Dan Brown',
    'Suzanne Collins',
    'Harper Lee',
    'F. Scott Fitzgerald',
    'Ernest Hemingway',
    'Mark Twain',
    'Leo Tolstoy',
    'Fyodor Dostoevsky',
    'Aldous Huxley',
    'Peter Straub',
    'Stephen Baxter',
    'Rob Wilkins',
    'Owen King',
    'Frank Herbert',
    'Aldous Huxley',
    'J.D. Salinger',
    'Cormac McCarthy',
    'Kurt Vonnegut',
    'Brent Weeks',
    'Haruki Murakami',
    'George Orwell',
    'Mary Shelley',
    'Oscar Wilde',
    'Bram Stoker',
    'Khaled Hosseini',
    'Yann Martel',
    'Markus Zusak',
    'Paulo Coelho',
    'Erin Morgenstern',
    'Gillian Flynn',
    'Brandon Sanderson',
    'Jane Austen',
    'John Green',
    'James Dashner'
);
