run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - dupl
    - goconst
    - gocognit

linters-settings:
  gocyclo:
    min-complexity: 10

issues:
  exclude-rules:
    - path: "_test.go"
      linters:
        - gocyclo
        - goconst
  max-issues-per-linter: 0
  max-same-issues: 0
